name: Pytest
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:    
      - name: Pytest
        uses: microsoft/action-python@0.7.0
        with:          
          testing: true
